# sbin path
export PATH="/usr/local/sbin:$PATH"

# Homebrew path
export PATH="/opt/homebrew/bin:$PATH"

#Python
export PATH="/opt/homebrew/lib/python3.10/site-packages/pip:$PATH"
export PATH="/Users/$USER/Library/Python/3.10/bin:$PATH"

#Ruby Gem
export GEM_HOME="$HOME/.gem"

# curl path
export PATH="/opt/homebrew/opt/curl/bin:$PATH"
export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"
export PATH="/opt/homebrew/opt/pyqt@5/5.15.6/bin:$PATH"

# Ruby path
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="$(gem environment gemdir)/bin:$PATH"

# Support 256 colors path
export TERM="xterm-256color"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"


# Android Configurations
if [ -f ~/.android ]; then
  source ~/.android
fi

# Flutter Configurations
if [ -f ~/.flutter ]; then
  source ~/.flutter
fi

# NVM Auto Load
if [ -f ~/.nvm-load ]; then
  source ~/.nvm-load
fi

#ALIAS
if [ -f ~/.bash_alias ]; then 
    source ~/.bash_alias;
fi

#BASHRC
if [ -f ~/.bashrc ]; then 
    source ~/.bashrc;
fi

#BREW
if [ -f ~/.brew ]; then 
    source ~/.brew;
fi