# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/bash_profile.pre.bash" ]] && . "$HOME/.fig/shell/bash_profile.pre.bash"
# sbin path
export PATH="/usr/local/sbin:$PATH"

# Homebrew path
export PATH="/opt/homebrew/bin:$PATH"

#Pip
export PATH="/opt/homebrew/lib/python3.9/site-packages/pip:$PATH"

#Ruby Gem
export GEM_HOME="$HOME/.gem"

# curl path
export PATH="/opt/homebrew/opt/curl/bin:$PATH"

# Ruby path
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="$(gem environment gemdir)/bin:$PATH"

# Support 256 colors path
export TERM="xterm-256color"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"


# Android Configurations
if [ -f ~/.android ]; then
  source ~/.android
fi

# Flutter Configurations
if [ -f ~/.flutter ]; then
  source ~/.flutter
fi

# NVM Auto Load
if [ -f ~/.nvm-load ]; then
  source ~/.nvm-load
fi

#ALIAS
if [ -f ~/.bash_alias ]; then 
    . ~/.bash_alias;
fi

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/bash_profile.post.bash" ]] && . "$HOME/.fig/shell/bash_profile.post.bash"
