source ~/.profile
export PATH="/usr/local/sbin:$PATH"

#ANDROID
# Create a JAVA_HOME variable, determined dynamically
export JAVA_HOME=$(/usr/libexec/java_home)
# Add that to the global PATH variable
export PATH=${JAVA_HOME}/bin:$PATH

# Set Android_HOME
export ANDROID_SDK_ROOT=~/Library/Android/sdk
# Add the Android SDK to the ANDROID_HOME variable
export PATH=${ANDROID_SDK_ROOT}/platform-tools:$PATH
export PATH=${ANDROID_SDK_ROOT}/build-tools/30.0.3:$PATH
export PATH=${ANDROID_SDK_ROOT}/tools:$PATH

#Set GRADLE_HOME
export GRADLE_HOME=/opt/homebrew/Cellar/gradle/7.1.1
export PATH=${GRADLE_HOME}/bin:$PATH

#Flutter
export PATH="/opt/homebrew/Caskroom/flutter/2.2.3/flutter/bin/flutter:$PATH"

export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

#ALIAS
if [ -f ~/.bash_alias ]; then 
    . ~/.bash_alias;
fi